version: "3.8" 
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-blog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blog_db
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpassword
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: bloguser
      PMA_PASSWORD: blogpassword
    ports:
      - "8080:80"
